// ProcessOuterCOMService.idl : ProcessOuterCOMService 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ProcessOuterCOMService.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(96992788-E884-4972-8C90-C964D03DFC5E),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IIOuterCOMExport : IDispatch{
    [id(1), helpstring("设置名称")] HRESULT SetName([in] BSTR strName);
    [id(2), helpstring("返回名称")] HRESULT GetName([out, retval] BSTR* strName);
};
[
	uuid(0530217D-E732-4F2B-A0EF-4E4952299DCE),
	version(1.0),
]
library ProcessOuterCOMServiceLib
{
	importlib("stdole2.tlb");
	[
		uuid(1B7351AC-671A-4131-957C-42DC82FCA70E)		
	]
	coclass IOuterCOMExport
	{
		[default] interface IIOuterCOMExport;
	};
};

